
DROP TABLE BLOODBAGINFO; 
DROP TABLE BLOODTRANSFERINFO; 
DROP TABLE RECIPIENT; 
DROP TABLE BLOODINFO; 
DROP TABLE DONOR; 
ALTER TABLE EMPLOYEESINFO DROP CONSTRAINT fk_employeesinfo;
DROP TABLE SCANNINGSYSTEM;
DROP TABLE EMPLOYEESINFO;


/* EMPLOYEESINFO TABLE CREATION*/
CREATE TABLE EMPLOYEESINFO (
EmpId NUMBER(10) NOT NULL,
FName VARCHAR(20)NOT NULL,
EmpSSN VARCHAR(10) NOT NULL,
Designation VARCHAR(25),
SysmID NUMBER(15),
Salary NUMBER(25)NOT NULL,
Address VARCHAR(50),
Contact VARCHAR(25)NOT NULL,
PRIMARY KEY(EmpId)
);


/* SCANNINGSYSTEM  TABLE CREATION*/
CREATE TABLE SCANNINGSYSTEM (
SysmID NUMBER(25)NOT NULL,
SysmName VARCHAR(25)NOT NULL,
Purpose VARCHAR(25),
EmpId NUMBER(25),
Quantity VARCHAR(10),
Cost VARCHAR(10),
ServiceHistory VARCHAR(35),
PRIMARY KEY(SysmId)
);


/* DONOR TABLE CREATION*/
CREATE TABLE DONOR (
DID NUMBER(10) NOT NULL PRIMARY KEY,
FName VARCHAR(10) NOT NULL,
DSSN VARCHAR(10),
Age VARCHAR(3),
Sex VARCHAR(10),
BloodGroup VARCHAR(5) NOT NULL,
DDate DATE,
Quantity VARCHAR(10),
PreownedDiseases VARCHAR(20),
Address VARCHAR(50),
Contact VARCHAR(10)NOT NULL
);


/* BLOODINFO TABLE CREATION*/
CREATE TABLE BLOODINFO (
PacketNo NUMBER(10) NOT NULL PRIMARY KEY,
BloodGroup VARCHAR(10)NOT NULL,
Quantity VARCHAR(10),
RBC VARCHAR(10),
WBC VARCHAR(10),
Platelets VARCHAR(10),
Haemoglobin VARCHAR(10),
PricePerML VARCHAR(10)
);


/* RECIPIENT TABLE CREATION*/
CREATE TABLE RECIPIENT (
RID NUMBER(10) NOT NULL PRIMARY KEY,
FName VARCHAR(10) NOT NULL,
RSSN VARCHAR(10),
Age VARCHAR(3),
Sex VARCHAR(10),
BloodPacketInjected NUMBER(5) NOT NULL,
Quantity VARCHAR(10),
Hospital VARCHAR(20),
DoctorReference VARCHAR(20),
Address VARCHAR(50),
Contact VARCHAR(10)NOT NULL,
Notice VARCHAR(20),
CONSTRAINT fk_recipt FOREIGN KEY (BloodPacketInjected) REFERENCES BLOODINFO(PacketNo)
);


/* BLOODTRANSFERINFO TABLE CREATION*/
CREATE TABLE BLOODTRANSFERINFO (
DID NUMBER(10),
BloodPacketNo NUMBER(10)NOT NULL,
RID NUMBER(10),
EmpId NUMBER(10),
CONSTRAINT fk_bloodtransfer FOREIGN KEY (BloodPacketNo) REFERENCES BLOODINFO(PacketNo),
CONSTRAINT fk_recipient FOREIGN KEY (RID) REFERENCES RECIPIENT(RID)
);


/*BLOODBAGINFO TABLE CREATION*/
CREATE TABLE BLOODBAGINFO (
BloodbagNo NUMBER(10) NOT NULL PRIMARY KEY,
BloodGroup VARCHAR(10),
PacketCount INT
);




