DROP PROCEDURE sp_Insert;

CREATE OR REPLACE PROCEDURE sp_Insert (
DID NUMBER,
FNAME VARCHAR,
DSSN VARCHAR,
AGE VARCHAR,
SEX VARCHAR,
BLOODGROUP VARCHAR,
DDATE DATE,
QUANTITY VARCHAR,
PREOWNEDDISEASES VARCHAR,
ADDRESS VARCHAR,
CONTACT VARCHAR
)
AS
VarID NUMBER(10) := DID;
VarNAME VARCHAR(20) := FNAME;
VarDSSN VARCHAR(20) := DSSN;
VarAGE VARCHAR(20) := AGE;
VarSEX VARCHAR(20) := SEX;
VarBLOODGROUP VARCHAR(20) := BLOODGROUP;
VarDate VARCHAR(20) :=  DDATE;
VarQuantity VARCHAR(20) := QUANTITY;
VarDiseases VARCHAR(20) := PREOWNEDDISEASES;
VarAddress VARCHAR(20) := ADDRESS;
VarContact VARCHAR(20) := CONTACT;

BEGIN

/*DELETE FROM EMPLOYEE WHERE ID = VarID;*/
INSERT INTO DONOR (DID, FNAME, DSSN, AGE, SEX, BLOODGROUP, DDATE, QUANTITY, PREOWNEDDISEASES, ADDRESS, CONTACT)
VALUES
(VarID, VarNAME, VarDSSN,VarAGE, VarSEX, VarBLOODGROUP,VarDate,  VarQuantity, VarDiseases, VarAddress,  VarContact);

END;
/




