 select * from donor;
 
CREATE OR REPLACE PROCEDURE sp_Select (
Var_DID         IN DONOR.DID%TYPE,
Var_DID_OUT     OUT DONOR.DID%TYPE,
Var_FNAME       OUT DONOR.FNAME%TYPE,
Var_AGE         OUT DONOR.AGE%TYPE,
Var_SEX         OUT DONOR.SEX%TYPE,
Var_BLOODGROUP  OUT DONOR.BLOODGROUP%TYPE

)
IS
BEGIN 
SELECT DID,FNAME,AGE,SEX,BLOODGROUP into Var_DID_OUT,Var_FNAME,Var_AGE,Var_SEX,Var_BLOODGROUP From Donor WHERE DID = Var_DID;

END;
/


