

DROP PROCEDURE sp_Update;

CREATE OR REPLACE PROCEDURE sp_Update (DONORID NUMBER, VarName VARCHAR, VarAGE VARCHAR, VarSEX VARCHAR ) AS

BEGIN

UPDATE DONOR
SET AGE = VarAge, SEX = VarSex
WHERE DID = DonorID AND FNAME = VarName;

END;
/
